version: '2'
services:
  redis:
    image: redis:latest
    command: --appendonly yes

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=testdb
    
  app-a:
    image: app-a:v1
    ports:
      - 8080:8080

    depends_on:
      - redis
      #- postgres

    links:
      - redis:redis
      #- postgres:postgres

  app-b:
    image: app-b:v1
    ports:
      - 8081:8081

    links:
      - redis:redis
      - app-a:app-a
      #- postgres:postgres

    volumes:
      - ".:/test-volume"


