version: '2'
services:
  redis:
    image: redis:latest
    command: --appendonly yes
    
  alpha:
    image: supinfosxb/alpha:v1
    ports:
      - 8080:8080

    depends_on:
      - redis

    links:
      - redis:redis

  beta:
    image: supinfosxb/beta:v1-alpine
    ports:
      - 8081:8081

    links:
      - redis:redis
      - alpha:alpha

    volumes:
      - ".:/test-volume"

  gamma:
    image: supinfosxb/gamma:v1
    ports:
      - 8082:8082

  omega:
    image: supinfosxb/omega:v1
    ports:
      - 3000:3000



