version: '2'
services:
  redis:
    image: redis:latest
    command: --appendonly yes
    
  app-alpha:
    image: app-alpha
    ports:
      - 8080:8080

    depends_on:
      - redis

    links:
      - redis:redis

  app-beta:
    image: app-beta
    ports:
      - 8081:8081

    links:
      - redis:redis
      - app-alpha:app-alpha

    volumes:
      - ".:/test-volume"


