apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    name: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
      name: redis
    spec:
      containers:
      - args:
        - --appendonly
        - "yes"
        image: redis:latest
        name: redis
        ports:
        - containerPort: 6739
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 250Mi
      restartPolicy: Always
