apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: alpha-deployment
  labels:
    name: alpha
spec:
  replicas: 3
  selector:
    matchLabels:
      name: alpha

  template:
    metadata:
      labels:
        name: alpha
    spec:
      containers:
      - name: alpha
        image: ahilaly/alpha:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 250Mi

      restartPolicy: Always
    
