version: 2
jobs:
  # Build job
  build:
    machine: true
    steps:
      - checkout
            
      - run:
          name: build alpha
          command: |
            make build-alpha

      - run:
          name: build beta alpine
          command: |
            make compile-beta
            make build-beta-alpine
            make build-omega
            make build-gamma

  # Build and push job
  build-push:
    machine: true
    steps:
      - checkout

      - run:
          name: build alpha
          command: |
            make build-alpha

      - run:
          name: build beta alpine
          command: |
            make compile-beta
            make build-beta-alpine
            make build-omega
            make build-gamma

      - run:
          name: docker login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
  
      - run:
          name: push
          command: |
            docker push supinfosxb/alpha:v1
            docker push supinfosxb/beta:v1-alpine
            docker push supinfosxb/gamma:v1
            docker push supinfosxb/omega:v1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
               - test
               - dev
               - /dev-.*/
      - build-push:
          filters:
            branches:
              only:
                - master