version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
            
      - run:
          name: build app-alpha
          command: |
            make build-alpha

      - run:
          name: build app-beta alpine
          command: |
            make compile-beta
            make build-beta-alpine
  build-push:
    machine: true
    steps:
      - checkout

      - run:
          name: build app-alpha
          command: |
            make build-alpha

      - run:
          name: build beta alpine
          command: |
            make compile-beta
            make build-beta-alpine

      - run:
          name: docker login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
  
      - run:
          name: push
          command: |
            docker push ahilaly/app-alpha:v1
            docker push ahilaly/app-beta:v1-alpine

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
               - test
               - dev
               - /dev-.*/
      - build-push:
          filters:
            branches:
              only:
                - master
                - dev