apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: app-alpha-deployment
  labels:
    name: app-alpha
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app-alpha

  template:
    metadata:
      labels:
        name: app-alpha
    spec:
      containers:
      - name: app-alpha
        image: ahilaly/app-alpha:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 250Mi

      restartPolicy: Always
    
