apiVersion: v1
kind: Pod
metadata:
  name: alpha-pod
  namespace: default
  labels:
    name: alpha
spec:

  containers:
  - name: alpha-pod
    image: ahilaly/alpha:v2
    ports:
      - containerPort: 8080
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 250Mi

  - name: beta-pod
    image: ahilaly/beta:v2-alpine
    ports:
      - containerPort: 8081
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 250Mi
