apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta-deployment
  labels:
    name: beta
spec:
  replicas: 3

  selector:
    matchLabels:
      name: beta

  template:
    metadata:
      labels:
        name: beta
    spec:
      containers:
      - name: beta
        image: ahilaly/beta:v1-alpine
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 250Mi

      restartPolicy: Always
    
