apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    name: app-beta
  name: app-beta
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    name: app-beta
  type: NodePort