apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
  labels:
    name: app-a
spec:
  replicas: 3

  selector:
    matchLabels:
      name: app-a

  template:
    metadata:
      labels:
        name: app-a
    spec:
      containers:
      - name: app-a
        image: ahilaly/app-a:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 250Mi

      restartPolicy: Always
    
