apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    name: app-a
  name: app-a
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    name: app-a
  type: LoadBalancer
